FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \

    && apt -y install gcc \
                      g++ \
                      build-essential \
                      cmake \
                      python3-dev \
                      python3-pip
